name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel 13
      uses: ./
      with:
          kernel-url: https://github.com/linex-17/kernel.git
          kernel-dir: msm-4.9
          kernel-branch: 13
          config: santoni_treble_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.7.6
          ksu-lkm: false
          nethunter: false
          nethunter-patch: false
          android-version: 12
          aosp-clang-version: r383902
          python-27: true
          disable-lto: true
          anykernel3: true
          
    
